In [6]:
import numpy as np
import pandas as pd
import nltk
import re
from nltk.corpus import reuters
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from collections import Counter
%load_ext autoreload
# quick summary of the reuters corpus
print(">>> The reuters corpus has {} tags".format(len(reuters.categories())))
print(">>> The reuters corpus has {} documents".format(len(reuters.fileids())))

>>> The reuters corpus has 90 tags
>>> The reuters corpus has 10788 documents


In [2]:
## Getting file name
reuters.fileids()[0]

'test/14826'

In [3]:
## Getting the word types in the file
reuters.categories(reuters.fileids()[0])

['trade']

In [4]:
## Getting the words in the file
len(reuters.words(reuters.fileids()))

1720901

In [98]:
## Getting words by category
reuters.words(categories='barley')

['FRENCH', 'FREE', 'MARKET', 'CEREAL', 'EXPORT', ...]

In [102]:
%autoreload
from vi_reuters import variational_inference
variational_inference(iterations=5,num_doc=1)

  0%|          | 0/5 [00:00<?, ?it/s]/home/aditya/Documents/Course_Work/fall_20/CSE 291 Deep Generative Modelling/vi_reuters.py:82: RuntimeWarning: invalid value encountered in double_scalars
  l4 = -np.log(Gamma(np.sum(gamma))) + np.sum(np.log(Gamma(gamma))) - np.sum((gamma-1) * (digamma_diff))
 60%|██████    | 3/5 [00:00<00:00,  8.55it/s]

Final -5456.736495663853
Final -5455.385212245029
Final -5454.506551451754


100%|██████████| 5/5 [00:00<00:00,  7.53it/s]

Final -5453.928095467967
Final -5453.542954255006


In [87]:
# %load_ext autoreload

In [34]:
sum(np.random.dirichlet(np.ones(10),(3))[0])

0.9999999999999999

In [36]:
a = np.random.dirichlet(np.ones(3),(4))

In [37]:
np.sum(a,axis=1)

array([1., 1., 1., 1.])

In [60]:
b= [1,3,4]
b = np.array(b)
c = b[np.newaxis,:]
d = c @ np.zeros((3,3))


array([[0., 0., 0.]])

In [62]:
a = np.arange(10)
b = np.zeros((10,10))
b[np.arange(10),a] = 1
b

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])